### ISSUE TITLE
librelist doesnt seem to work

### ISSUE THREAD

**Issue by giorgosp** [swistakm/graceful#36]
Hi,

I have sent both an empty email and a normal email to graceful at librelist.com but nothing happens

**Comment by swistakm** [comment]
Oh, that sucks. I have tested it with my company email and I confirm that it doesn't work.

Since, graceful@librelist.com had nothing in it's archive I think we can switch to something else. Any ideas? Google groups?

Until we decide a best solution or community will grow to the size that will require group I have made a group on gitter. See gitter badge in `README.md` and in PR #37. I think that we can move the discussion on this topic to gitter. Let's close this.
